<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Customer::insert([
            [
                'name'           => 'Finns Beach Club',
                'address'        => 'Jalan Pantai Berawa, Canggu',
                'state'          => 'Badung',
                'province'       => 'Bali',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '7',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Agro Puncak',
                'address'        => 'Jl.Raya Bedugul',
                'state'          => 'Tabanan',
                'province'       => 'Bali',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '081337423666',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '0',
            ],
            [
                'name'           => 'Montigo Resort',
                'address'        => 'JL.Petitenget',
                'state'          => 'Kuta Utara',
                'province'       => 'Bali',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Tandoor Jimbaran',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Tandoor Seminyak',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Finns Recreation Club',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Hard Rock Cafe',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Soori Bali',
                'address'        => 'Banjar Dukuh, Desa Kelating, Kerambitan, Tabanan, Bali 82161, Indonesia',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Saputra',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Kupu Kupu Jimbaran',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'cafe delmar bali',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'CAFE DELMAR',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Retail Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'VILLA LUMBUNG',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'D&R',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Laci Resto',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Parachute Bali',
                'address'        => 'Jl.Subak sari 13 no.8-4,Canggu,Kec.Kuta utara,Kabupaten Badung,Bali',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => 'Horeca Customer',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Risata bali resort & Spa',
                'address'        => '',
                'state'          => '',
                'province'       => '',
                'postcode'       => '',
                'country'        => '',
                'work_phone'     => '',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
            [
                'name'           => 'Kupu Kupu Barong Ubud',
                'address'        => 'Kedewatan Ubud Bali',
                'state'          => 'Gianyar',
                'province'       => 'Bali',
                'postcode'       => 'PO BOX 7',
                'country'        => '',
                'work_phone'     => '(0361)975478',
                'payment_terms'  => '',
                'customer_type'  => '',
                'send_reminders' => '1',
            ],
        ]);
    }
}
